### ISSUE TITLE
Error when using  pnpm dlx create-sheriff-config

### ISSUE THREAD

**Issue by g5becks** [AndreaPontrandolfo/sheriff#124]
Error: Invalid Options:
- Unknown options: reportUnusedDisableDirectives
- 'reportUnusedDisableDirectives' has been removed. Please use the 'overrideConfig.linterOptions.reportUnusedDisableDirectives' option instead.

Error: Invalid Options:
- Unknown options: reportUnusedDisableDirectives
- 'reportUnusedDisableDirectives' has been removed. Please use the 'overrideConfig.linterOptions.reportUnusedDisableDirectives' option instead.

**Comment by AndreaPontrandolfo** [comment]
Hey @g5becks i see you closed the issue. Was this a false-positive?

**Comment by g5becks** [comment]
> Hey @g5becks i see you closed the issue. Was this a false-positive?

No, the error ended up being specific to webstorm.

Thanks.

**Comment by AndreaPontrandolfo** [comment]
ok, no problem!
