### ISSUE TITLE
Improve Astro support

### ISSUE THREAD

**Issue by chalkygames123** [AndreaPontrandolfo/sheriff#130]
Hi,

Thank you so much for adding support for Astro in #45, and I'm sorry for the silence.

I just tried the latest Sheriff on my Astro projects and noticed a few issues.

1. The default import of Astro components has to be named in Pascal case so it can be used as an HTML tag name (see: https://docs.astro.build/en/core-concepts/astro-syntax/#dynamic-tags). So, the [`@typescript-eslint/naming-convention` rule](https://github.com/AndreaPontrandolfo/sheriff/blob/5c84d2524a0dfd18fa7229d8b81fc123b3c787ee/packages/eslint-config-sheriff/src/getTsNamingConventionRule.ts#L9-L55) needs to be updated like this:

```diff
         selector: "typeProperty",
         format: null,
       },
+      {
+        selector: "import",
+        format: ["camelCase", "PascalCase"],
+      },
     ],
   };
 };
```

2. Astro's [built-in components](https://docs.astro.build/en/reference/api-reference/#built-in-components) import specifier starts with `'astro:'`, so the [`import/no-unresolved` rule](https://github.com/AndreaPontrandolfo/sheriff/blob/5c84d2524a0dfd18fa7229d8b81fc123b3c787ee/packages/eslint-config-sheriff/src/importHandPickedRules.ts#L6) needs to be updated like this:

```diff
   'import/namespace': 0,
   'import/default': 0,
   'import/no-named-as-default-member': 0,
-  'import/no-unresolved': [2, { commonjs: true, caseSensitiveStrict: true }],
+  'import/no-unresolved': [2, { commonjs: true, caseSensitiveStrict: true, ignore: ['^astro:.+'] }],
   'import/first': 2,
   'import/order': [2, { 'newlines-between': 'never' }],
   'import/no-default-export': 2,
```

I'm happy to send PRs if you want.

**Comment by AndreaPontrandolfo** [comment]
Hey @chalkygames123 thank you for the great feedback again! 

I'll look into these.

**Comment by chalkygames123** [comment]
About #1, I also noticed that it conflicts with the naming convention that Astro requires for endpoint functions. See: https://docs.astro.build/en/guides/endpoints/#http-methods

**Comment by AndreaPontrandolfo** [comment]
@chalkygames123 
i also started a little astro support update here https://github.com/AndreaPontrandolfo/sheriff/pull/128, but it's unrelated to the problems that you are highlighting.
The problem is that the `@typescript-eslint/naming-convention` rule in itself is already pretty complex, so i need to look into this carefully. Then we can work together for the solution and you can submit the PR if you want.
In the meantime you can override the rule, just for the astro files, with your own implementation.

**Comment by chalkygames123** [comment]
Thank you for the update.

I agree that it is pretty complex, and I'm not sure if there is a simple solution.

I'm sorry, but I don't have much time, so I'd like to leave you the PR and final decision. That said, please feel free to let me know if you want me to test your PR in my project.

I'm working around with [`patch-package`](https://github.com/ds300/patch-package), so it's not a problem for the time being.

**Comment by chalkygames123** [comment]
In case you didn't know, I just wanted to share a shareable config, [`@antfu/eslint-config`](https://github.com/antfu/eslint-config), which is quite informative and inspiring (off-topic, sorry).

**Comment by chalkygames123** [comment]
Oh yes! I had missed that line.

Yeah, `@antfu/eslint-config` is "very personal and opinionated," as he notes himself, so I have to admit I could not accept its formatting style. Also, the strictness of its rules is currently limited. Rather, I find its configurability with `eslint-flat-config-utils` and the auto-detection of languages/frameworks to be remarkable.

It may also be worthwhile to incorporate [`@eslint/config-inspector`](https://github.com/eslint/config-inspector) into the [Rules](https://www.eslint-config-sheriff.dev/docs/rules) doc.

Anyway, I am looking forward to seeing Sheriff evolve further!

**Comment by AndreaPontrandolfo** [comment]
I had a look at [eslint-flat-config-utils](https://github.com/antfu/eslint-flat-config-utils), it seems mildly interesting but honestly i'm having a hard time figuring  out what those utils are for. The documentation is kinda scarce.
The FlatConfig format is very powerful and surprisingly easy and straightforward to use, those utils seems fairly redundant and seem to re-introduce most of the complications of the old eslintrc format for no reason.
I think i don't see the usefulness of that but please if you have more insights on that let me know.
Also note that internally Sheriff use the `tseslint.config` util, provided by `@typescript-eslint` library.

**Comment by AndreaPontrandolfo** [comment]
@chalkygames123 related to your second point https://github.com/ota-meshi/eslint-plugin-astro/issues/300

**Comment by AndreaPontrandolfo** [comment]
I tried to have a look at this, but the `eslint-plugin-astro` is still very early. It changes very rapidly (they do like weekly releases) and it has tons of compatibility issues with other stuff. On-top of the fact that also Astro changes very rapidly.
Also the docs are all scattered around, they reference the old eslintrc config a lot and the eslint-typescript is unclear.
I'll let `eslint-plugin-astro` stabilize a bit in the next few months and then i'll revisit.

**Comment by lishaduck** [comment]
I updated Astro as part of #157. item 1 seems to be the default for tseslint, and we aren't customizing it, so ¯\\\_(ツ)\_/¯. Item 2 was corrected though.
