### ISSUE TITLE
404 error in new install

### ISSUE THREAD

**Issue by YPCrumble** [AndreaPontrandolfo/sheriff#150]
Thanks for creating this great package! I'm trying to migrate from xo and found your repo [here](https://github.com/xojs/xo/issues/702#issuecomment-1437219821).

I'm getting this error on `npx create-sheriff-config`:

```
Need to install the following packages:
create-sheriff-config@5.1.2
Ok to proceed? (y) y
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@sherifforg%2fconstants - Not found
npm ERR! 404
npm ERR! 404  '@sherifforg/constants@0.0.1' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by AndreaPontrandolfo** [comment]
Hey @YPCrumble thank you!

I think npm is trying to install @sherifforg/constants, which is a private package that Sheriff uses internally. It doesn't exists in NPM and rightly so.
But im not sure to understand why npm is trying to install it.
Will dig deeper on this.

**Comment by AndreaPontrandolfo** [comment]
Hey @YPCrumble,

So, it was a bundling issue, TSUP wasn't bundling `@sherifforg/constants` inside the other libs.

It's all good now, i'm gonna release the new version with this fix just now. Thank you so much for the report!
