### ISSUE TITLE
Make Astro optional

### ISSUE THREAD

**Issue by lishaduck** [AndreaPontrandolfo/sheriff#153]
Like React, I'd like it if Astro support was optional.
I think astro is great project, but it slows down linting to include it by default.
The plugin also doesn't work on bun: _https://github.com/PSDTools/GPA_Calculator/actions/runs/9149492515/job/25153166809_.
It's an ignorable error, but it's not pretty.

I'd be willing to PR this.

**Comment by AndreaPontrandolfo** [comment]
This is something I have been thinking about. At this point I consider it a early design mistake.
If you are willing to submit a PR I'll review it right away, go for it, that'd be great!

**Comment by lishaduck** [comment]
I think I've got it!
It works in my vanilla-ts bun monorepo, is there a good astro project I can test it on?

**Comment by lishaduck** [comment]
I just want to note that this issue is even worse than it used to be:

```console
Oops! Something went wrong! :(

ESLint: 8.57.0

Error: 1 | file:///Users/dukese01/Developer/psdtools.github.io/node_modules/astrojs-compiler-sync/lib/astrojs-compiler-worker-service.mjs
                                                                                                                                 ^
error: Unexpected end of file
    at blob:7c20edf9-dbff-4c26-8d65-e70651adfb67:1:126
    at #onError (node:worker_threads:189:11)
```

**Comment by lishaduck** [comment]
> I just want to note that this issue is even worse than it used to be:
> 
> ```
> Oops! Something went wrong! :(
> 
> ESLint: 8.57.0
> 
> Error: 1 | file:///Users/dukese01/Developer/psdtools.github.io/node_modules/astrojs-compiler-sync/lib/astrojs-compiler-worker-service.mjs
>                                                                                                                                  ^
> error: Unexpected end of file
>     at blob:7c20edf9-dbff-4c26-8d65-e70651adfb67:1:126
>     at #onError (node:worker_threads:189:11)
> ```

Easy workaround: upgrade Sheriff to 18.5 from 18.1.
