### ISSUE TITLE
Don't require installing `@typescript-eslint/parser`

### ISSUE THREAD

**Issue by lishaduck** [AndreaPontrandolfo/sheriff#166]
For some reason, PNPM makes me install `@typescript-eslint/parser` as a peer dependency of Sheriff, rather than doing so automatically as a dependency. This should be investigated and fixed.

**Comment by AndreaPontrandolfo** [comment]
Depending on the version of PNPM, the `auto-install-peers` flag can be default `true` or default `false`.

**Comment by lishaduck** [comment]
> Depending on the version of PNPM, the `auto-install-peers` flag can be default `true` or default `false`.

It defaults to true, there's not a conflict. It's probably a bug in pnpm, but just making note of it in case there's a bug in packaging I need to cover in #161.

**Comment by lishaduck** [comment]
I'm going to close this, we can see if it's still relevant with ESLint 9 + TSESLint 8

**Comment by lishaduck** [comment]
For future reference, I think this was fixed in PNPM 9.7 (pnpm/pnpm#8323)

**Comment by AndreaPontrandolfo** [comment]
Indeed PNPM 9.5 was kind of a broken release.
I'll update to 9.7 in the next release, for sure.

**Comment by lishaduck** [comment]
> Indeed PNPM 9.5 was kind of a broken release. I'll update to 9.7 in the next release, for sure.

This was a bug installing it in my project, not installing the sheriff monorepo itself.
PNPM 9 is probably a worthwhile upgrade though.
