### ISSUE TITLE
New blog post

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [AndreaPontrandolfo/sheriff#167]
With the release of eslint-config-sheriff V19, the new major, we should publish a new blog post.

Highlights:

- [x] https://github.com/AndreaPontrandolfo/sheriff/issues/185
- [x] https://github.com/AndreaPontrandolfo/sheriff/issues/209

~~I think we can save ESLint V9 support for the next major and the next blogpost.~~

**Comment by lishaduck** [comment]
Not sure why there's a help wanted label, but I'm happy to pedantically copyedit it 😜

**Comment by lishaduck** [comment]
Oh, and assuming #161 is merged in time, our size is going to 📉
I'd call that a highlight.

**Comment by lishaduck** [comment]
Are we delaying remeda until v20?

**Comment by AndreaPontrandolfo** [comment]
Eh, I don't have a specific timeline for the inclusion

**Comment by AndreaPontrandolfo** [comment]
@lishaduck sorry it took me this long to get back to this, i'm having to pretty intense IRL stuff lately lol

Anyway, i would absolutely love to have your help in crafting this blogpost, and actually i want to include a special thank you to you @lishaduck in the footnotes for all the progress that you enabled on Sheriff!

**Comment by lishaduck** [comment]
> @lishaduck sorry it took me this long to get back to this, i'm having to pretty intense IRL stuff lately lol

That's fine, no need to apologize 😁

> Anyway, i would absolutely love to have your help in crafting this blogpost, and actually i want to include a special thank you to you @lishaduck in the footnotes for all the progress that you enabled on Sheriff!

Thanks!
To clarify, this would be the v20 post now? I feel like v19 was rather minor, though I'm not complaining if there are more regular posts.

**Comment by AndreaPontrandolfo** [comment]
I would like to summarize pretty much everything that was done since the last blogpost up until now (and i'll also try to make a cool graphic, like with the other 2 posts).
I would like it to be reflective about what worked and what didn't, lately,
Also it should mention the direction where Sheriff is headed and the future steps.

**Comment by lishaduck** [comment]
> I would like to summarize pretty much everything that was done since the last blogpost up until now (and i'll also try to make a cool graphic, like with the other 2 posts).
> I would like it to be reflective about what worked and what didn't, lately, Also it should mention the direction where Sheriff is headed and the future steps.

Ah. Well, that makes sense. Please ping me when you've got something! (though please don't feel any pressure to prioritize it, I'm just a random guy who wanted to adopt flat-config early a year or so ago and decided this looked cool)

**Comment by lishaduck** [comment]
P.S. CI is failing in my projects because that typo got fixed! Hurrah for TypeScript not letting me merge an incomplete dependabot PR! (and thanks for Sheriff!)
