### ISSUE TITLE
Remove `eslint-config-prettier`

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [AndreaPontrandolfo/sheriff#180]
I just realized that after the stylistic rules of `@eslint/js` and `@typescript-eslint/eslint-plugin` moved to `@stylistic/eslint-plugin`, this library isn't doing anything anymore for us.
The only rule of `@stylistic/eslint-plugin` that we are using right now doesn't conflict with prettier.
`eslint-config-prettier` is now completely redundant and we can remove it.
Now we can also move `curly: [2, 'all']` to the `getBaseEslintHandPickedRules.ts` file.
We'll also need to update the docs accordingly `apps/docs-website/docs/prettier-support.md`.

**Comment by lishaduck** [comment]
One thing to note might be configs that include `@stylistic` rules. I think there were a few of those, though they don't conflict currently so it's probably fine 🤷‍♂️

**Comment by AndreaPontrandolfo** [comment]
I think we don't include any other "config", just "plugins".

**Comment by lishaduck** [comment]
> I think we don't include any other "config", just "plugins".

As in, plugin configs. I thought that the eslint-config-inspector showed a few stylistic rules enabled, but maybe not.
