### ISSUE TITLE
[ADD] `eslint-plugin-regexp`

### ISSUE THREAD

**Issue by lishaduck** [AndreaPontrandolfo/sheriff#195]
Prevent bad regexes from leaking into code.
~~With TS 5.5 and Unicorn, it's probably not necessary, but I'm in an issue filing mood.~~ It does catch a lot more, including some security stuff.

Link: [`npm:eslint-plugin-regexp`](https://www.npmjs.com/package/eslint-plugin-regexp)

**Comment by AndreaPontrandolfo** [comment]
Ya, TS added some stuff in a later release but nothing comparable to this plugin. I think we should remove the [unicorn rule](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/better-regex.md) and add this plugin.
