### ISSUE TITLE
Transition to native Typescript support

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [AndreaPontrandolfo/sheriff#201]
[ESLint now supports eslint.config.{ts,cts,mts} natively](https://eslint.org/blog/2024/08/eslint-v9.9.0-released/#experimental-typescript-configuration-files). We should adopt that instead of our custom implementation with [eslint-ts-patch](https://github.com/antfu/eslint-ts-patch).

Requirements:

- [ ] https://github.com/microsoft/vscode-eslint/issues/1917

**Comment by AndreaPontrandolfo** [comment]
BLOCKED BY: https://github.com/microsoft/vscode-eslint/issues/1917

**Comment by lishaduck** [comment]
Fixed by #225?
I saw some parts in the diff about ts.

**Comment by AndreaPontrandolfo** [comment]
Oh no, we are still on [antfu/eslint-ts-patch](https://github.com/antfu/eslint-ts-patch).
I'm waiting for the dust to settle on https://github.com/microsoft/vscode-eslint/issues/1917 before migrating.

**Comment by AndreaPontrandolfo** [comment]
Sooooo, i just realized that it's pointless to wait for https://github.com/microsoft/vscode-eslint/issues/1917 anyway. 
https://github.com/microsoft/vscode-eslint/issues/1917 is a problem with the ESLint VSCode extension, not with the ESLint implementation of TS support, so it doesn't make sense to hold this for that.
