### ISSUE TITLE
Remove CJS support for config file

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [AndreaPontrandolfo/sheriff#222]
`eslint.config.js` with CJS syntax has been broken for months now.
The issue started when i integrated [eslint-config-flat-gitignore](https://github.com/antfu/eslint-config-flat-gitignore). 
`eslint-config-flat-gitignore` is not compatible with CJS and will throw an error at runtime if `eslint.config.js` is treated as a CJS module (funnily enough, it was my _own_ [PR](https://github.com/antfu/eslint-config-flat-gitignore/pull/8) that broke CJS support).

Now, considering that the config file can be .mjs file without any drawback ([@antfu/eslint-config](https://github.com/antfu/eslint-config) also adopt this approach), and even better it should be a .ts file, i see no downsides to removing the CJS support all togheter.

**Comment by lishaduck** [comment]
This'd also drastically simplify #161.

I think it'd _better_ to fix `eslint-config-flat-gitignore`, but if `@`antfu didn't want to bundle `find-up-simple`, I'd be understanding.

**Comment by AndreaPontrandolfo** [comment]
I mean, this is the exact outcome that Sindresorhus wants, i'm not going against the will of that guy haha.

**Comment by lishaduck** [comment]
Thanks! I've been slowly rewriting #161 and this'll make it much easier (if not obsolete)
The only thing I didn't realize is that we'll run into arethetypeswrong/arethetypeswrong.github.io#112, which is a shame (tl;dr: attw'll fail without esm/node10 support until there's an option for esm-only packages, so we can't run it in ci)

**Comment by AndreaPontrandolfo** [comment]
I think this might does the trick? https://github.com/andrewbranch/example-subpath-exports-ts-compat.

I'm not sure, will have to check.

**Comment by lishaduck** [comment]
> I think this might does the trick? https://github.com/andrewbranch/example-subpath-exports-ts-compat.
> 
> I'm not sure, will have to check.

I was going to say no, but actually it should work:
https://github.com/andrewbranch/example-subpath-exports-ts-compat/tree/main/examples/node_modules/types-versions-wildcards

Doesn't work at runtime though, so I'd argue it's still wrong. One ought to be using modern moduleResolution settings.
