### ISSUE TITLE
Bump Node in CI

### ISSUE THREAD

**Issue by lishaduck** [AndreaPontrandolfo/sheriff#230]
Sheriff needs 20 (internally at least), but CI only runs 18.
I _think_ that's why #229 keeps failing despite working file locally (latest stable/22)

**Comment by lishaduck** [comment]
Oh, forgot to ping you, @AndreaPontrandolfo.

Can you do this on master, then I can rebase and 🤞 it works?

**Comment by AndreaPontrandolfo** [comment]
yup, i just realized it needs

```
with: 
  node-version-file: package.json
```

in order to actually respect the package.json.
