### ISSUE TITLE
Dogfood

### ISSUE THREAD

**Issue by lishaduck** [AndreaPontrandolfo/sheriff#236]
Turbo dislikes circular dependencies, which makes this difficult, but we should be able to lint the Sheriff monorepo using `eslint-config-sheriff`.
I was able to get it working for 99% of the repo in #162, but it's got a ton of conflicts now.
It's valuable that whenever we enforce something new, we have to feel it and decide if it's worth it ourselves.

**Comment by AndreaPontrandolfo** [comment]
It's unfortunate it got mangled by conflicts, the whole PR was pretty much perfect 😢
