### ISSUE TITLE
Configuration rules for react broken

### ISSUE THREAD

**Issue by nahtnam** [AndreaPontrandolfo/sheriff#244]
Full error:
```
Oops! Something went wrong! :(

ESLint: 9.9.1

Configuration for rule "@eslint-react/0,off" is invalid. Each rule must have a severity ("off", 0, "warn", 1, "error", or 2) and may be followed by additional options for the rule.

You passed 'undefined', which doesn't contain a valid severity.

If you're attempting to configure rule options, perhaps you meant:

    "@eslint-react/0,off": ["error", undefined]

See https://eslint.org/docs/latest/use/configure/rules#using-configuration-files for configuring rules.

 ELIFECYCLE  Command failed with exit code 2.
```

Reproduced here: https://codesandbox.io/p/devbox/sheriff-broken-99vwxg

**Comment by AndreaPontrandolfo** [comment]
Thank you for the report @nahtnam !

I'm investigating. Not sure what's the problem exactly yet, but most likely it's in this piece of code `...rel1cxReact.configs.off,`.

In the meantime, as a band aid, setting `react: false` in the `SheriffOptions`, will stop the crash.

**Comment by AndreaPontrandolfo** [comment]
It's very strange because the error definitely exist, but for some reason it doesn't manifest in `apps\config-validation-playground`.

I commented the lines regarding` @eslint-react/eslint-plugin`, and the error vanished, so that's definitely the culpript.

**Comment by AndreaPontrandolfo** [comment]
Soooo... removing the `off` configuration and defining the plugin manually fixes the issue.
So the  `off` config is broken, not sure why.

Anyway, i'll bundle the fix with the next release.
Gonna release soon™️
