### ISSUE TITLE
Disable certain rules for next.js

### ISSUE THREAD

**Issue by nahtnam** [AndreaPontrandolfo/sheriff#251]
It would be great if the following rules were disabled for the app folder (could be in either `/app` or `/src/app`):

```
import/no-default-export - every tsx/jsx file has a default export
react/function-component-definition - its common for next.js apps to just do `export default function Page() {}`, seems weird to enforce switching to `export default const Page = () => {}`
@typescript-eslint/explicit-module-boundary-types - return type seems redundant, every file in a route file will be returning a jsx element
react-refresh/only-export-components - jsx/tsx files often export config or metadata functions and files
```

**Comment by nahtnam** [comment]
I know we are entering opinionated territory but I personally believe if `next: true` then `function-component-definition` should go from anonymous components to function declaration for consistency (pretty much all next.js docs use `export function`)

**Comment by AndreaPontrandolfo** [comment]
Hey @nahtnam , great suggestions!

> import/no-default-export - every tsx/jsx file has a default export

Sure, i will PR this.

> I know we are entering opinionated territory but I personally believe if next: true then function-component-definition should go from anonymous components to function declaration for consistency (pretty much all next.js docs use export function)

Sure, makes sense.

> @typescript-eslint/explicit-module-boundary-types - return type seems redundant, every file in a route file will be returning a jsx element

Mmmm, i still find this valuable. I'll keep this. If some user don't want this, they can disable it easily anyway.

> react-refresh/only-export-components - jsx/tsx files often export config or metadata functions and files

Mmm, i think i'll put my trust in the developer of that plugin and let it do it's thing. The plugin ensures that HMR will keep working is JSX files. I don't think anybody wants broken HMR in next.js files.
