### ISSUE TITLE
Possible to pass a custom tsconfig.json file for parserOptions.project?

### ISSUE THREAD

**Issue by joshuaja** [AndreaPontrandolfo/sheriff#27]
I'm getting the following ESLint error due to the `files` sherriff config option being different from what is in the tsconfig.json file:

```
Parsing error: ESLint was configured to run on `<tsconfigRootDir>/.file.js` using `parserOptions.project`: 'tsconfig.json' 
However, that TSConfig does not include this file.
```

Is it possible to pass a path to a custom tsconfig.json file. I see that it is expecting that filename specifically in the sheriff code.

**Comment by AndreaPontrandolfo** [comment]
Hi @joshuaja !
Are you trying to use Sheriff on a .js file?
Currently Sheriff is made specifically for Typescript codebases. 
If you are trying to lint .js files with Sheriff, i cannot provide further support.
Please refer to the documentation: https://github.com/AndreaPontrandolfo/sheriff#-introduction

If this is not the case, please provide more details to help me clarify the situation.

**Comment by joshuaja** [comment]
@AndreaPontrandolfo - I'm inheriting a repo that uses multiple tsconfig.json files. There is a separate tsconfig.eslint.json file in the repo that is used for the linter config. Because tsconfig.json is hard-coded into the Sheriff config I cannot use the custom tsconfig.eslint.json file that is currently there.

Hope this helps!

**Comment by AndreaPontrandolfo** [comment]
@joshuaja 
So, if i understand correctly, you are referring to this line: https://github.com/AndreaPontrandolfo/sheriff/blob/0fb4da771a6afe184294d9061e5a270ccc2a2e99/configs/eslint.config.js#L522
It points to your tsconfig.json, but you want it to point to your tsconfig.eslint.json.
I think i can make this dynamic and expose a setting in the sheriffOptions. It would let you do what you want.
I'll work on this asap. In the meantime, let me know if this would solve your usecase.

**Comment by joshuaja** [comment]
You would so need to change it in the languageOptionsTypescript function but yes, this would solve the use case perfectly. Thank you!

**Comment by AndreaPontrandolfo** [comment]
@joshuaja  fixed in the latest release https://github.com/AndreaPontrandolfo/sheriff/releases/tag/v11.6.0 !
