### ISSUE TITLE
SheriffSettings is not exported from `eslint-config-sheriff`

### ISSUE THREAD

**Issue by sangrepura** [AndreaPontrandolfo/sheriff#270]
![image](https://github.com/user-attachments/assets/9f4729a9-b460-4565-939f-58c748005e55)

It is from `@sherifforg/types`

![image](https://github.com/user-attachments/assets/377bb76a-3b87-4c29-bb05-9f337f31cf3e)

**Comment by AndreaPontrandolfo** [comment]
@sangrepura yeah i know, sheriff-types is meant to be deprecated and the docs are correct, but unfortunately i had trouble with actually deploying to NPM the latest version of the config, so now there is this mismatch (i had a problem with changesets)
This weekend i should have time to actually release the new version and ship some new stuff aswell.

**Comment by AndreaPontrandolfo** [comment]
Hey @sangrepura thanks for the feedback and sorry for the delay!

Everything should be good now, i managed to defeat `changeset` and published the new version of `eslint-config-sheriff` that should contain the types (again, `@sherifforg/types` is now completely deprecated).

I really struggled with `changeset` this time around, it's an ambitious piece of software, but is completely riddled with bugs and undocumented behaviors.
