### ISSUE TITLE
Update `return-await` mode

### ISSUE THREAD

**Issue by lishaduck** [AndreaPontrandolfo/sheriff#285]
By [default](https://github.com/typescript-eslint/typescript-eslint/blob/4af866a6642502117c32b49e64d7012a027c42f5/packages/eslint-plugin/src/configs/strict-type-checked-only.ts#L72), it's set to `error-handling-correctness-only`, but [the docs](https://typescript-eslint.io/rules/return-await/) recommend setting it `always` or `in-try-catch`. Personally, I prefer the `always` style (it's consistent, has better stacktraces, and equal perf[^1])

[^1]: Originally, it had worse perf (4 ticks vs 2), but they changed the spec so it's faster (1 tick vs 2), but then changed plain return to also use 1 tick, so perf is moot unless you're targeting older targets.

**Comment by lishaduck** [comment]
Also, I noticed we didn't use `stylisticTypeChecked` from tseslint. I assume that's because sheriff has it's own opinions?

**Comment by AndreaPontrandolfo** [comment]
> Also, I noticed we didn't use `stylisticTypeChecked` from tseslint. I assume that's because sheriff has its own opinions?

Yep, that's exactly right, we don't care about stylisticTypeChecked.

**Comment by AndreaPontrandolfo** [comment]
> By [default](https://github.com/typescript-eslint/typescript-eslint/blob/4af866a6642502117c32b49e64d7012a027c42f5/packages/eslint-plugin/src/configs/strict-type-checked-only.ts#L72), it's set to `error-handling-correctness-only`, but [the docs](https://typescript-eslint.io/rules/return-await/) recommend setting it `always` or `in-try-catch`. Personally, I prefer the `always` style (it's consistent, has better stacktraces, and equal perf[1](#user-content-fn-1-f63b7b162667ae480b8ca3c18a207108))
> 
> ## Footnotes
> 1. Originally, it had worse perf (4 ticks vs 2), but they changed the spec so it's faster (1 tick vs 2), but then changed plain return to also use 1 tick, so perf is moot unless you're targeting older targets. [↩](#user-content-fnref-1-f63b7b162667ae480b8ca3c18a207108)

I see.

After reading https://github.com/typescript-eslint/typescript-eslint/issues/10165 i will hold on to this.

This change could be controversial and could emerge a lot noisy warnings in codebases, while being basically just a stylistic improvement.

I think it's better to wait for the dust to settle on https://github.com/typescript-eslint/typescript-eslint/issues/10165 and then we can make a better-informed decision. Chances are that they decide to enable it by default in the strict config and we don't have to do anything.

**Comment by lishaduck** [comment]
> After reading [typescript-eslint/typescript-eslint#10165](https://github.com/typescript-eslint/typescript-eslint/issues/10165) i will hold on to this.

Oh, I hadn't seen that. Glad to see that there's ecosystem-wide progress on it! +1 to putting this on pause then.
I guess I'll close this? Feel free to reopen if you'd prefer to leave it open.
