### ISSUE TITLE
Replace `eslint-config-flat-gitignore` with `@eslint/compat`

### ISSUE THREAD

**Issue by lishaduck** [AndreaPontrandolfo/sheriff#304]
We already depend on `@eslint/compat`, so, unless there's major behavioral differences, we might as well drop the redundant `eslint-config-flat-gitignore` in favor of [`includeIgnoreFile`](https://github.com/eslint/rewrite/tree/main/packages/compat#including-ignore-files).

**Comment by AndreaPontrandolfo** [comment]
> Could also let us restore CJS compat, though I don't see the point to doing that, especially with `require(esm)` and `module-sync`.

You are right in that it would allow us to restore CJS compat... but we don't necessarily need it. I think we are past that at this point.

What's `module-sync`?

**Comment by lishaduck** [comment]
> You are right in that it would allow us to restore CJS compat... but we don't necessarily need it. I think we are past that at this point.

I agree! ESM simplifies bundling significantly.

> What's `module-sync`?

It's [a new `exports` condition](https://nodejs.org/en/blog/release/v22.10.0#new-module-sync-exports-condition) for modules that want to support `require(esm)` without breaking the ecosystem.

**Comment by AndreaPontrandolfo** [comment]
> We already depend on `@eslint/compat`, so, unless there's major behavioral differences, we might as well drop the redundant `eslint-config-flat-gitignore` in favor of [`includeIgnoreFile`](https://github.com/eslint/rewrite/tree/main/packages/compat#including-ignore-files).

This is interesting, but i think there are atleast 2 problems with this:

1. if i'm reading right, this option isn't monorepo-friendly

    > Limitation: This works without modification when the ignore file is in the same directory as your config file. If the ignore file is in a different directory, you may need to modify the patterns manually.

   While `eslint-config-flat-gitignore` [is](https://github.com/antfu/eslint-config-flat-gitignore/releases/tag/v0.1.3).

2. we will probably remove `@eslint/compat` dependency in the near future, once storybook and nextjs will not need it anymore.

Also it's important to note that apparently `eslint-config-flat-gitignore` is already [somewhat leveraging `@eslint/compat` internally](https://github.com/antfu/eslint-config-flat-gitignore/releases/tag/v0.2.0), which lead me to believe that moving to `@eslint/compat` would be a straight-up downgrade from the as-is.

**Comment by lishaduck** [comment]
> 1. if i'm reading right, this option isn't monorepo-friendly
>    > Limitation: This works without modification when the ignore file is in the same directory as your config file. If the ignore file is in a different directory, you may need to modify the patterns manually.
>    
>    
>    While `eslint-config-flat-gitignore` [is](https://github.com/antfu/eslint-config-flat-gitignore/releases/tag/v0.1.3).

It looks like they both take an array of paths relative to the `eslint.config.(m|c)?(j|t)s` file, or else grab the nearest gitignore to the config, the only difference is that the compat version doesn't fall back to searching upward if your `eslint.config.js` file isn't by a gitignore. So they both work, the compat version is just a bit more work.

> 2. we will probably remove `@eslint/compat` dependency in the near future, once storybook and nextjs will not need it anymore.
> 
> Also it's important to note that apparently `eslint-config-flat-gitignore` is already [somewhat leveraging `@eslint/compat` internally](https://github.com/antfu/eslint-config-flat-gitignore/releases/tag/v0.2.0), which lead me to believe that moving to `@eslint/compat` would be a straight-up downgrade from the as-is.

If `eslint-config-flat-gitignore` uses it either way, then storybook & nextjs supporting v9 doesn't make a difference, right?

---

I still think it'd be reasonable to switch, but I admit the ergonomics wouldn't be as good.
