### ISSUE TITLE
Sheriff attempting to use Storybook rules in normal TS files

### ISSUE THREAD

**Issue by rahulp959** [AndreaPontrandolfo/sheriff#43]
I'm running a normal TS project, no FE involved, just some API development.

The problem I currently face is that Sheriff is trying to use Storybook rules in normal `index.ts` files.

Example screenshot below:

<img width="717" alt="image" src="https://github.com/AndreaPontrandolfo/sheriff/assets/342885/32840cf5-7526-4b04-9598-3675f272c5ba">

Any chance this can be updated so Storybook rules are only inserted in Storybook files?

**Comment by rahulp959** [comment]
I think #44  should do it.

**Comment by rahulp959** [comment]
Hey!

Any thoughts on the PR?

**Comment by AndreaPontrandolfo** [comment]
Hey man, thank you for raising the issues!

Yah, Storybook support has been kind of pain.
I tested your PR, but unfortunately it wasn't working.
I investigated the issue and i think the paths that `eslint-plugin-storybook` provides are not valid for `eslint.config.js` syntax.
`Eslint.config.js` syntax for paths uses `minimatch`.
I'm going to release the fix in a few minutes.
