### ISSUE TITLE
[feature request] eslint-plugin-tailwindcss 

### ISSUE THREAD

**Issue by Talent30** [AndreaPontrandolfo/sheriff#77]
Hi, there.

This is an amazing project. Would you consider add tailwindcss eslint plugin as an option please?

https://github.com/francoismassart/eslint-plugin-tailwindcss

**Comment by AndreaPontrandolfo** [comment]
Hey @Talent30! Appreciated!

I took a look at https://github.com/francoismassart/eslint-plugin-tailwindcss.
There are currently no plans to integrate `eslint-plugin-tailwindcss` in Sheriff, however you can install it manually yourself, right after Sheriff.
It should be pretty easy, just follow the instructions on their [README](https://github.com/francoismassart/eslint-plugin-tailwindcss#installation)  and adapt it to the [FlatConfig](https://eslint.org/docs/latest/use/configure/configuration-files-new).

Let me know if you run into any specific trouble!
