### ISSUE TITLE
Cannot find any type declaration files of "SheriffSettings" in eslint-config-sheriff

### ISSUE THREAD

**Issue by KevinKVJ** [AndreaPontrandolfo/sheriff#92]
I want to look up the "SheriffSettings" type declaration of the package when I configure it.  I found it in your github monorepo called "sheriff-type".. However I realize that it is a seperated package in your repo, probably not build. I tried downloading it and it pop up 404 not found... Should it be contained in "eslint-config-sheriff" package or as a seperated package on official npm repo?

![image](https://github.com/AndreaPontrandolfo/sheriff/assets/47245225/e0f9ea2d-d783-4796-b35f-ab9ebd975411)

**Comment by AndreaPontrandolfo** [comment]
I didn't publish it to npm.

**Comment by KevinKVJ** [comment]
> I didn't publish it to npm.

Do you have a plan to push it?

**Comment by AndreaPontrandolfo** [comment]
@KevinKVJ it was meant for internal development but i can plan to publish it in some form, yes.

**Comment by KevinKVJ** [comment]
Perfect! I get it!! Thank you!
