### ISSUE TITLE
Deprecation of Formatting Rules in ESLint v8.53

### ISSUE THREAD

**Issue by Talent30** [AndreaPontrandolfo/sheriff#99]
Hi, @AndreaPontrandolfo,

ESLint is [deprecating](https://eslint.org/blog/2023/10/deprecating-formatting-rules/) all the formatting rules, providing us with two alternatives for migration.

1. Remove all the formatting rules in xo. Instead, we recommend users to utilise a code formatter, such as Prettier. This is the recommended approach.

2. Migrate all the formatting rules to [ESLint Stylistic](https://eslint.style/).

**Comment by AndreaPontrandolfo** [comment]
Hey @Talent30 , thank you for the headsup!

Actually i was already aware of that. It's not really an issue, i think we currently have just 1 or 2 formatting rules. Migrating those to [ESLint Stylistic](https://eslint.style) will likely require just a trivial pull-request.

Not a big deal, will do that in a short time.
